name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup foreman
        uses: rojo-rbx/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build asset rbxm
        run: rojo build build.project.json -o SmallOctree.rbxm

      - name: Git Release
        uses: anton-yurchenko/git-release@v3.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          ALLOW_EMPTY_CHANGELOG: "true"
          ALLOW_TAG_PREFIX: "false"
          CHANGELOG_FILE: "CHANGELOG.md"
          RELEASE_NAME_PREFIX: "SmallOctree"
        with:
          args: |
              ./SmallOctree.rbxm